FROM ubuntu:latest
RUN apt-get update -y 
RUN apt-get upgrade -y
RUN apt install default-jdk -y
RUN mkdir /opt/tomcat
WORKDIR /opt/tomcat
ADD https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.85/bin/apache-tomcat-9.0.85.tar.gz .
RUN tar -xvzf apache-tomcat-9.0.85.tar.gz
RUN mv apache-tomcat-9.0.85/* /opt/tomcat
COPY ./webapp.jar /opt/tomcat/webapps
EXPOSE 8080
CMD ["/opt/tomcat/bin/catalina.sh", "run"]
